name: api_wether
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/Image_05-02-1445_AH_at_9.55_PM-removebg-preview.png
    - assets/Wind weather lines group symbol ⋆ Free Vectors, Logos, Icons and Photos Downloads.png